# Generated by Django 4.1.7 on 2023-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FloodReport",
            fields=[
                (
                    "flood_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Flood Susceptibility",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(max_length=255, verbose_name="Municipality"),
                ),
                (
                    "barangay_name",
                    models.CharField(max_length=255, verbose_name="Barangay"),
                ),
                ("purok_name", models.CharField(max_length=255, verbose_name="Purok")),
                ("household", models.IntegerField(verbose_name="No. of Households")),
                ("families", models.IntegerField(verbose_name="No. of Families")),
                ("person", models.IntegerField(verbose_name="No. of Persons")),
                ("num_male", models.IntegerField(verbose_name="Individuals (M)")),
                ("num_female", models.IntegerField(verbose_name="Individuals (F)")),
                (
                    "num_male_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (M)"),
                ),
                (
                    "num_female_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (F)"),
                ),
                (
                    "num_male_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (M)"),
                ),
                (
                    "num_female_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (F)"),
                ),
                (
                    "num_male_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (M)"),
                ),
                (
                    "num_female_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (F)"),
                ),
                (
                    "num_male_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (M)"),
                ),
                (
                    "num_female_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (F)"),
                ),
                ("num_pwd_male", models.IntegerField(verbose_name="PWD (M)")),
                ("num_pwd_female", models.IntegerField(verbose_name="PWD (F)")),
                ("num_ip_male", models.IntegerField(verbose_name="IP (M)")),
                ("num_ip_female", models.IntegerField(verbose_name="IP (F)")),
            ],
            options={
                "verbose_name_plural": "Flood",
                "db_table": "flood_report",
            },
        ),
        migrations.CreateModel(
            name="LandslideReport",
            fields=[
                (
                    "ril_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Landslide Susceptibility",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(max_length=255, verbose_name="Municipality"),
                ),
                (
                    "barangay_name",
                    models.CharField(max_length=255, verbose_name="Barangay"),
                ),
                ("household", models.IntegerField(verbose_name="No. of Households")),
                ("purok_name", models.CharField(max_length=255, verbose_name="Purok")),
                ("families", models.IntegerField(verbose_name="No. of Families")),
                ("person", models.IntegerField(verbose_name="No. of Persons")),
                ("num_male", models.IntegerField(verbose_name="Individuals (M)")),
                ("num_female", models.IntegerField(verbose_name="Individuals (F)")),
                (
                    "num_male_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (M)"),
                ),
                (
                    "num_female_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (F)"),
                ),
                (
                    "num_male_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (M)"),
                ),
                (
                    "num_female_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (F)"),
                ),
                (
                    "num_male_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (M)"),
                ),
                (
                    "num_female_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (F)"),
                ),
                (
                    "num_male_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (M)"),
                ),
                (
                    "num_female_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (F)"),
                ),
                ("num_ip_male", models.IntegerField(verbose_name="IP (M)")),
                ("num_ip_female", models.IntegerField(verbose_name="IP (F)")),
            ],
            options={
                "verbose_name_plural": "Landslide",
                "db_table": "landslide_report",
            },
        ),
        migrations.CreateModel(
            name="StormSurgeReport",
            fields=[
                (
                    "ss_id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Storm Surge Susceptibility",
                    ),
                ),
                (
                    "municipality_name",
                    models.CharField(max_length=255, verbose_name="Municipality"),
                ),
                (
                    "barangay_name",
                    models.CharField(max_length=255, verbose_name="Barangay"),
                ),
                ("purok_name", models.CharField(max_length=255, verbose_name="Purok")),
                ("household", models.IntegerField(verbose_name="No. of Households")),
                (
                    "families",
                    models.IntegerField(null=True, verbose_name="No. of Families"),
                ),
                ("person", models.IntegerField(verbose_name="No. of Persons")),
                ("num_male", models.IntegerField(verbose_name="Individuals (M)")),
                ("num_female", models.IntegerField(verbose_name="Individuals (F)")),
                (
                    "num_male_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (M)"),
                ),
                (
                    "num_female_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (F)"),
                ),
                (
                    "num_male_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (M)"),
                ),
                (
                    "num_female_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (F)"),
                ),
                (
                    "num_male_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (M)"),
                ),
                (
                    "num_female_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (F)"),
                ),
                (
                    "num_male_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (M)"),
                ),
                (
                    "num_female_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (F)"),
                ),
                ("num_ip_male", models.IntegerField(verbose_name="IP (M)")),
                ("num_ip_female", models.IntegerField(verbose_name="IP (F)")),
            ],
            options={
                "verbose_name_plural": "Storm Surge",
                "db_table": "stormsurge_report",
            },
        ),
    ]
