# Generated by Django 4.1 on 2023-06-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stormsurgereport",
            old_name="surge_id",
            new_name="ssid",
        ),
    ]
