# Generated by Django 4.1 on 2023-06-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_rename_surge_id_stormsurgereport_ssid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floodreport",
            options={
                "permissions": [
                    ("view_report", "Can view report"),
                    ("change_report", "Can change report"),
                ],
                "verbose_name_plural": "Flood",
            },
        ),
        migrations.AlterModelOptions(
            name="landslidereport",
            options={
                "permissions": [
                    ("view_report", "Can view report"),
                    ("change_report", "Can change report"),
                ],
                "verbose_name_plural": "Landslide",
            },
        ),
        migrations.AlterModelOptions(
            name="stormsurgereport",
            options={
                "permissions": [
                    ("view_report", "Can view report"),
                    ("change_report", "Can change report"),
                ],
                "verbose_name_plural": "Storm Surge",
            },
        ),
    ]
