# Generated by Django 4.1 on 2022-08-10 20:54

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import household.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0031_alter_municipalities_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Households",
            fields=[
                ("controlnumber", models.TextField(primary_key=True, serialize=False)),
                ("purok", models.CharField(max_length=25, null=True)),
                ("longitude", models.CharField(max_length=50, null=True)),
                ("latitude", models.CharField(max_length=50, null=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("respondent", models.CharField(max_length=50)),
                ("date_interview", models.DateField(verbose_name="Date interviewed")),
                ("enumerator", models.CharField(max_length=50)),
                ("editor", models.CharField(max_length=50)),
                (
                    "year_construct",
                    models.IntegerField(
                        default=2022,
                        validators=[
                            django.core.validators.MinValueValidator(1940),
                            household.models.max_value_current_year,
                        ],
                        verbose_name="Building/House year construct",
                    ),
                ),
                ("estimated_cost", models.IntegerField()),
                ("number_bedrooms", models.SmallIntegerField()),
                ("number_storey", models.SmallIntegerField()),
                (
                    "access_electricity",
                    models.BooleanField(verbose_name="Access to electricity"),
                ),
                (
                    "access_internet",
                    models.BooleanField(verbose_name="Access to internet"),
                ),
                ("medical_treatment", models.TextField(null=True)),
                (
                    "access_water_supply",
                    models.BooleanField(verbose_name="Access to water supply"),
                ),
                ("potable", models.BooleanField(verbose_name="Safe to drink")),
                (
                    "floods_occur",
                    models.BooleanField(verbose_name="Flood occur in your area"),
                ),
                (
                    "year_flooded",
                    models.IntegerField(
                        default=2022,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1940),
                            household.models.max_value_current_year,
                        ],
                    ),
                ),
                (
                    "experience_evacuate",
                    models.BooleanField(
                        verbose_name="Experience evacuation during calamity"
                    ),
                ),
                (
                    "year_evacuate",
                    models.IntegerField(
                        default=2022,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1940),
                            household.models.max_value_current_year,
                        ],
                    ),
                ),
                (
                    "access_health_medical_facility",
                    models.BooleanField(
                        verbose_name="Access to health and medical facility"
                    ),
                ),
                (
                    "access_telecommuniciation",
                    models.BooleanField(verbose_name="Access to telecommunication"),
                ),
                (
                    "access_drill_simulation",
                    models.BooleanField(
                        verbose_name="Access/Join drill and simulation"
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="uploads/")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "barangay",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.barangays",
                        verbose_name="Barangay",
                    ),
                ),
                (
                    "evacuationareas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.evacuationareas",
                        verbose_name="Nearest evacuation center",
                    ),
                ),
                (
                    "householdbuildingtypes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.householdbuildingtypes",
                        verbose_name="Building types",
                    ),
                ),
                (
                    "householdroofmaterials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.householdroofmaterials",
                        verbose_name="Roof material",
                    ),
                ),
                (
                    "householdtenuralstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.householdtenuralstatus",
                        verbose_name="Tenural status",
                    ),
                ),
                (
                    "householdwallmaterials",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.buildingwallmaterials",
                        verbose_name="Wall material",
                    ),
                ),
                (
                    "householdwatertenuralstatus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.householdwatertenuralstatus",
                        verbose_name="Water tenural status",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.municipalities",
                        verbose_name="Municipality",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waterlevelsystems",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.waterlevelsystems",
                        verbose_name="Level of water system",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Households",
            },
        ),
    ]
