# Generated by Django 4.1 on 2022-08-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0002_demographies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="ethnicity_by_blood",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Belongs to tribe/enthics"
            ),
        ),
    ]
