# Generated by Django 4.1 on 2022-08-11 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0003_alter_demographies_ethnicity_by_blood"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demographies",
            old_name="course_compleated_vocational",
            new_name="course_completed_vocational",
        ),
    ]
