# Generated by Django 4.1 on 2022-08-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "household",
            "0004_rename_course_compleated_vocational_demographies_course_completed_vocational",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="nuclear_family",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="household.demographies",
                verbose_name="Nuclear family belongs to",
            ),
        ),
    ]
