# Generated by Django 4.1 on 2022-08-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0032_alter_buildingstatus_options_and_more"),
        ("household", "0005_alter_demographies_nuclear_family"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="type_of_disability",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.disabilities",
            ),
        ),
    ]
