# Generated by Django 4.1 on 2022-08-11 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0032_alter_buildingstatus_options_and_more"),
        ("household", "0007_demographies_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="controlnumber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="household.households",
                verbose_name="Housedhold belong",
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="current_grade_level_attending",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_attending",
                to="library.gradelevels",
            ),
        ),
    ]
