# Generated by Django 4.1 on 2022-08-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0032_alter_buildingstatus_options_and_more"),
        ("household", "0008_alter_demographies_controlnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="course_completed_vocational",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.trackstrandcourses",
                verbose_name="Track/Strand/Course completed (for senior High school/Vocational/College)",
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="nutritional_status_recorded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="primary_occupation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="type_of_disability",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.disabilities",
            ),
        ),
    ]
