# Generated by Django 4.1 on 2022-08-11 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0032_alter_buildingstatus_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("household", "0009_alter_demographies_course_completed_vocational_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availprograms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_program", models.CharField(max_length=150)),
                ("number_of_beneficiaries", models.SmallIntegerField()),
                ("program_implementor", models.CharField(max_length=150)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "controlnumber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.households",
                        verbose_name="Housedhold belong",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type_of_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.typeofprograms",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Avail Programs",
            },
        ),
    ]
