# Generated by Django 4.1 on 2022-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0013_alter_hhlivelihoods_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhlivelihoods",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
