# Generated by Django 4.1 on 2022-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0017_alter_demographies_ethnicity_by_blood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="households",
            name="medical_treatment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
