
# Generated by Django 4.1 on 2022-10-06 21:50


import django.core.validators
from django.db import migrations, models
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0018_alter_households_medical_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='year_construct',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1940), household.models.max_value_current_year], verbose_name='Building/House year construct'),
        ),
        migrations.AlterField(
            model_name='households',
            name='year_evacuate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1940), household.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='households',
            name='year_flooded',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1940), household.models.max_value_current_year]),
        ),
    ]
