# Generated by Django 4.1 on 2022-10-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0032_alter_buildingstatus_options_and_more'),
        ('household', '0020_alter_households_year_evacuate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availprograms',
            name='controlnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.households', verbose_name='Housedhold belong'),
        ),
        migrations.AlterField(
            model_name='availprograms',
            name='type_of_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.typeofprograms'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='controlnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.households', verbose_name='Housedhold belong'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.genders', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='monthly_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.monthlyincomes'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='nutritional_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.nutritionalstatus'),
        ),
        migrations.AlterField(
            model_name='demographies',
            name='relationshiptohead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.relationshiptoheads', verbose_name='Relationship to head'),
        ),
        migrations.AlterField(
            model_name='hhlivelihoods',
            name='controlnumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.households', verbose_name='Housedhold belong'),
        ),
        migrations.AlterField(
            model_name='hhlivelihoods',
            name='livelihood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.livelihoods'),
        ),
        migrations.AlterField(
            model_name='hhlivelihoods',
            name='livelihood_tenural_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.livelihoodtenuralstatus'),
        ),
        migrations.AlterField(
            model_name='households',
            name='barangay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.barangays', verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='households',
            name='evacuationareas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.evacuationareas', verbose_name='Nearest evacuation center'),
        ),
        migrations.AlterField(
            model_name='households',
            name='householdbuildingtypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.householdbuildingtypes', verbose_name='Building types'),
        ),
        migrations.AlterField(
            model_name='households',
            name='householdroofmaterials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.householdroofmaterials', verbose_name='Roof material'),
        ),
        migrations.AlterField(
            model_name='households',
            name='householdtenuralstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.householdtenuralstatus', verbose_name='Tenural status'),
        ),
        migrations.AlterField(
            model_name='households',
            name='householdwallmaterials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.buildingwallmaterials', verbose_name='Wall material'),
        ),
        migrations.AlterField(
            model_name='households',
            name='householdwatertenuralstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.householdwatertenuralstatus', verbose_name='Water tenural status'),
        ),
        migrations.AlterField(
            model_name='households',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.municipalities', verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='households',
            name='waterlevelsystems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.waterlevelsystems', verbose_name='Level of water system'),
        ),
    ]
