# Generated by Django 4.1 on 2023-03-06 06:37

import django.core.validators
from django.db import migrations, models
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0021_alter_availprograms_controlnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="households",
            name="year_flooded",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1940),
                    household.models.max_value_current_year,
                ],
            ),
        ),
    ]
