# Generated by Django 4.1 on 2023-03-09 02:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0033_purok"),
        ("household", "0021_alter_availprograms_controlnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="purok_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="library.purok",
                verbose_name="Purok",
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="middlename",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="year_flooded",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1940),
                    household.models.max_value_current_year,
                ],
            ),
        ),
    ]
