# Generated by Django 4.1 on 2023-03-24 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0022_alter_households_year_flooded"),
        (
            "household",
            "0022_households_purok_id_alter_demographies_middlename_and_more",
        ),
    ]

    operations = []
