# Generated by Django 4.1 on 2023-03-24 01:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0024_remove_households_purok_id_alter_households_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="households",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326
            ),
        ),
    ]
