# Generated by Django 4.1 on 2023-04-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0024_remove_households_purok_id_alter_households_location"),
    ]

    operations = []
