# Generated by Django 4.1 on 2023-04-13 00:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0033_purok"),
        ("household", "0025_auto_20230412_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="purok_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.purok",
                verbose_name="Purok",
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
