# Generated by Django 4.1 on 2023-04-28 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0035_familyrelationship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("household", "0026_households_purok_fk_alter_households_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Families",
            fields=[
                (
                    "fam_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "family_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="household.demographies",
                        verbose_name="Family Head",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="household.households",
                        verbose_name="Household belong",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="library.familystatus",
                        verbose_name="Family Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
            },
        ),
        migrations.CreateModel(
            name="Familydetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remarks", models.CharField(max_length=150)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "fam_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.families",
                        verbose_name="Family head",
                    ),
                ),
                (
                    "fam_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="household.demographies",
                        verbose_name="Family member",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.familyrelationship",
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.familystatus",
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Member",
                "verbose_name_plural": "Family Members",
            },
        ),
    ]
