# Generated by Django 4.1 on 2023-03-24 01:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0026_alter_households_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorRivers",
            fields=[
                ("gid", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.IntegerField(blank=True, null=True)),
                ("riv_name", models.CharField(blank=True, max_length=30, null=True)),
                ("area", models.FloatField(blank=True, null=True)),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "major_rivers",
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="households",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
