# Generated by Django 4.1 on 2023-03-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0028_alter_households_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="majorrivers",
            options={},
        ),
    ]
