# Generated by Django 4.1 on 2023-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0028_alter_demographies_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="families",
            name="remarks",
            field=models.CharField(default="N/A", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="familydetails",
            name="remarks",
            field=models.CharField(default="N/A", max_length=150, null=True),
        ),
    ]
