# Generated by Django 4.1.7 on 2023-09-18 07:36

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import household.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("library", "0039_alter_barangays_owner_alter_municipalities_owner_and_more"),
        ("household", "0029_alter_families_remarks_alter_familydetails_remarks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demographies",
            options={
                "verbose_name": "Individual",
                "verbose_name_plural": "Individuals",
            },
        ),
        migrations.AlterField(
            model_name="availprograms",
            name="owner",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="can_read_and_write",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Can read and write"
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="currently_attending_school",
            field=models.BooleanField(
                null=True, verbose_name="Currently attending in school"
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="dependent_of_philhealth_member",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="gsis_member",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="informal_settler",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="is_ofw",
            field=models.BooleanField(null=True, verbose_name="Is OFW"),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="member_ip",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Member of IP's"
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="person_with_special_needs",
            field=models.BooleanField(
                null=True, verbose_name="Person w/ special needs"
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="philhealth_member",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="religion",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="residence",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="sss_member",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="families",
            name="family_head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="household.demographies",
                verbose_name="Head of the family",
            ),
        ),
        migrations.AlterField(
            model_name="families",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="familydetails",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="familydetails",
            name="relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.familyrelationship",
                verbose_name="Relationship to head",
            ),
        ),
        migrations.AlterField(
            model_name="familydetails",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.familystatus",
                verbose_name="Family status",
            ),
        ),
        migrations.AlterField(
            model_name="hhlivelihoods",
            name="owner",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_drill_simulation",
            field=models.BooleanField(
                null=True, verbose_name="Access/Join drill and simulation"
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_electricity",
            field=models.BooleanField(null=True, verbose_name="Access to electricity"),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_health_medical_facility",
            field=models.BooleanField(
                null=True, verbose_name="Access to health and medical facility"
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_internet",
            field=models.BooleanField(null=True, verbose_name="Access to internet"),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_telecommuniciation",
            field=models.BooleanField(
                null=True, verbose_name="Access to telecommunication"
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="access_water_supply",
            field=models.BooleanField(null=True, verbose_name="Access to water supply"),
        ),
        migrations.AlterField(
            model_name="households",
            name="editor",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="enumerator",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="estimated_cost",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="floods_occur",
            field=models.BooleanField(
                null=True, verbose_name="Flood occur in your area"
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="households",
            name="number_bedrooms",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="number_storey",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="potable",
            field=models.BooleanField(null=True, verbose_name="Safe to drink"),
        ),
        migrations.AlterField(
            model_name="households",
            name="respondent",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="households",
            name="year_construct",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1940),
                    household.models.max_value_current_year,
                ],
                verbose_name="Building/House year construct",
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="year_evacuate",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    household.models.max_value_current_year,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="year_flooded",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    household.models.max_value_current_year,
                ],
            ),
        ),
    ]
