# Generated by Django 4.1 on 2023-04-03 01:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0029_alter_majorrivers_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorrivers",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
