# Generated by Django 4.1 on 2023-04-03 01:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0030_alter_majorrivers_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="households",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
