# Generated by Django 4.1.7 on 2023-10-02 03:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ("library", "0039_alter_barangays_owner_alter_municipalities_owner_and_more"),
        (
            "household",
            "0030_alter_demographies_options_alter_availprograms_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="demographies",
            name="can_read_and_write",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Can read & write"
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="extension",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Ext."
            ),
        ),
        migrations.AlterField(
            model_name="demographies",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="library.genders",
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="households",
            name="year_construct",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    household.models.max_value_current_year,
                ],
                verbose_name="Building/House year construct",
            ),
        ),
    ]
