# Generated by Django 4.1.7 on 2023-10-02 03:17

import django.core.validators
from django.db import migrations, models
import household.models


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0031_alter_demographies_can_read_and_write_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="households",
            name="purok",
        ),
        migrations.AlterField(
            model_name="households",
            name="year_construct",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    household.models.max_value_current_year,
                ],
                verbose_name="Building/House year construct",
            ),
        ),
    ]
