# Generated by Django 4.1.7 on 2023-10-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("household", "0032_remove_households_purok_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familydetails",
            name="status",
        ),
    ]
