# Generated by Django 4.1.7 on 2024-03-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0033_remove_familydetails_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availprograms',
            options={'verbose_name_plural': 'Availed Programs'},
        ),
        migrations.AlterField(
            model_name='households',
            name='experience_evacuate',
            field=models.BooleanField(verbose_name='Experienced evacuation during calamity'),
        ),
        migrations.AlterField(
            model_name='households',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
