# Generated by Django 4.1 on 2022-10-06 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0032_alter_buildingstatus_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Familiesandpopulation",
            fields=[
                ("fp_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("num_of_individuals_m", models.IntegerField()),
                ("num_of_individuals_f", models.IntegerField()),
                ("num_of_infant_m", models.IntegerField()),
                ("num_of_infant_f", models.IntegerField()),
                ("num_of_children_m", models.IntegerField()),
                ("num_of_children_f", models.IntegerField()),
                ("num_of_adult_m", models.IntegerField()),
                ("num_of_adult_f", models.IntegerField()),
                ("num_of_elderly_m", models.IntegerField()),
                ("num_of_elderly_f", models.IntegerField()),
                ("num_of_pwd_m", models.IntegerField()),
                ("num_of_pwd_f", models.IntegerField()),
                ("num_of_ip_m", models.IntegerField()),
                ("num_of_ip_f", models.IntegerField()),
                (
                    "barangay",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.barangays",
                        verbose_name="Barangay",
                    ),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.municipalities",
                        verbose_name="Municipality",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Families and Population",
                "ordering": ["municipality", "barangay"],
            },
        ),
    ]
