# Generated by Django 4.1 on 2023-03-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregate", "0002_familiesandpopulation_num_of_family"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familiesandpopulation",
            options={
                "ordering": ["municipality", "barangay"],
                "verbose_name_plural": "No. of families and population",
            },
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_adult_f",
            field=models.IntegerField(verbose_name="Adult 18-59y/o (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_adult_m",
            field=models.IntegerField(verbose_name="Adult 18-59y/o (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_children_f",
            field=models.IntegerField(verbose_name="Children 1-17y/o (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_children_m",
            field=models.IntegerField(verbose_name="Children 1-17y/o (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_elderly_f",
            field=models.IntegerField(verbose_name="Elderly 60y/o above (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_elderly_m",
            field=models.IntegerField(verbose_name="Elderly 60y/o above (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_family",
            field=models.IntegerField(default=0, verbose_name="No. of Families"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_individuals_f",
            field=models.IntegerField(verbose_name="Individuals (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_individuals_m",
            field=models.IntegerField(verbose_name="Individuals (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_infant_f",
            field=models.IntegerField(verbose_name="Infant 0-11months (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_infant_m",
            field=models.IntegerField(verbose_name="Infant 0-11months (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_ip_f",
            field=models.IntegerField(verbose_name="IP (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_ip_m",
            field=models.IntegerField(verbose_name="IP (M)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_pwd_f",
            field=models.IntegerField(verbose_name="PWD (F)"),
        ),
        migrations.AlterField(
            model_name="familiesandpopulation",
            name="num_of_pwd_m",
            field=models.IntegerField(verbose_name="PWD (M)"),
        ),
    ]
