# Generated by Django 4.1 on 2023-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aggregate", "0003_alter_familiesandpopulation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregatedFamiliesandPopulation",
            fields=[
                (
                    "munname",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Municipality",
                    ),
                ),
                (
                    "brgyname",
                    models.CharField(max_length=50, null=True, verbose_name="Barangay"),
                ),
                (
                    "households",
                    models.IntegerField(default=0, verbose_name="No. of Households"),
                ),
                (
                    "male",
                    models.IntegerField(default=0, verbose_name="Individuals (M)"),
                ),
                ("female", models.IntegerField(verbose_name="Individuals (F)")),
                (
                    "male_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (M)"),
                ),
                (
                    "female_infant",
                    models.IntegerField(verbose_name="Infant 0-11months (F)"),
                ),
                (
                    "male_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (M)"),
                ),
                (
                    "female_children",
                    models.IntegerField(verbose_name="Children 1-17y/o (F)"),
                ),
                ("male_adult", models.IntegerField(verbose_name="Adult 18-59y/o (M)")),
                (
                    "female_adult",
                    models.IntegerField(verbose_name="Adult 18-59y/o (F)"),
                ),
                (
                    "male_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (M)"),
                ),
                (
                    "female_elderly",
                    models.IntegerField(verbose_name="Elderly 60y/o above (F)"),
                ),
                ("ip_male", models.IntegerField(verbose_name="IP (M)")),
                ("ip_female", models.IntegerField(verbose_name="IP (F)")),
            ],
            options={
                "verbose_name_plural": "No. of families and population",
                "db_table": "aggregate",
            },
        ),
    ]
