# Generated by Django 4.1 on 2023-10-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adnflood',
            name='objectid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adnflood',
            name='shape_area',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='adnflood',
            name='shape_leng',
            field=models.FloatField(),
        ),
    ]
