# Generated by Django 4.1 on 2023-10-25 03:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_adnflood_objectid_alter_adnflood_shape_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('barangayna', models.IntegerField()),
                ('brgypsgc', models.CharField(max_length=255)),
                ('brgyarea', models.FloatField()),
                ('provname', models.CharField(max_length=255)),
                ('munname', models.CharField(max_length=255)),
                ('provpsgc', models.IntegerField()),
                ('regname', models.CharField(max_length=255)),
                ('regpsgc', models.IntegerField()),
                ('munpsgc', models.IntegerField()),
                ('brgypopn', models.CharField(max_length=255)),
                ('popden', models.FloatField()),
                ('munarea', models.FloatField()),
                ('munpopn', models.FloatField()),
                ('avehhsize', models.FloatField()),
                ('land_sus', models.CharField(max_length=255)),
                ('area_ha', models.FloatField()),
                ('arm_confli', models.FloatField()),
                ('mining_are', models.FloatField()),
                ('flooded', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
