# Generated by Django 4.1 on 2023-10-25 04:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
