# Generated by Django 4.1 on 2023-10-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_barangay_geom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barangay',
            options={'managed': False},
        ),
    ]
