# Generated by Django 4.1 on 2023-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_householdinfo_alter_barangay_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Householdpermun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('munname', models.CharField(blank=True, max_length=255, null=True)),
                ('households', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'householdpermun',
                'managed': False,
            },
        ),
    ]
