# Generated by Django 4.1 on 2023-12-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_floodreportperbarangay'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverAllFloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flood_id', models.CharField(blank=True, max_length=50, null=True)),
                ('household', models.BigIntegerField(blank=True, null=True)),
                ('families', models.BigIntegerField(blank=True, null=True)),
                ('person', models.BigIntegerField(blank=True, null=True)),
                ('num_male', models.BigIntegerField(blank=True, null=True)),
                ('num_female', models.BigIntegerField(blank=True, null=True)),
                ('num_male_infant', models.BigIntegerField(blank=True, null=True)),
                ('num_female_infant', models.BigIntegerField(blank=True, null=True)),
                ('num_male_children', models.BigIntegerField(blank=True, null=True)),
                ('num_female_children', models.BigIntegerField(blank=True, null=True)),
                ('num_male_adult', models.BigIntegerField(blank=True, null=True)),
                ('num_female_adult', models.BigIntegerField(blank=True, null=True)),
                ('num_male_elderly', models.BigIntegerField(blank=True, null=True)),
                ('num_female_elderly', models.BigIntegerField(blank=True, null=True)),
                ('num_ip_male', models.BigIntegerField(blank=True, null=True)),
                ('num_ip_female', models.BigIntegerField(blank=True, null=True)),
                ('num_pwd_male', models.BigIntegerField(blank=True, null=True)),
                ('num_pwd_female', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'over_all_flood_report',
                'managed': False,
            },
        ),
    ]
