# Generated by Django 4.1 on 2024-01-04 03:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_overallfloodreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdHouseholds',
            fields=[
                ('controlnumber', models.TextField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('respondent', models.CharField(blank=True, max_length=50, null=True)),
                ('date_interview', models.DateField()),
                ('enumerator', models.CharField(blank=True, max_length=50, null=True)),
                ('editor', models.CharField(blank=True, max_length=50, null=True)),
                ('year_construct', models.IntegerField(blank=True, null=True)),
                ('estimated_cost', models.IntegerField(blank=True, null=True)),
                ('number_bedrooms', models.SmallIntegerField(blank=True, null=True)),
                ('number_storey', models.SmallIntegerField(blank=True, null=True)),
                ('access_electricity', models.BooleanField(blank=True, null=True)),
                ('access_internet', models.BooleanField(blank=True, null=True)),
                ('medical_treatment', models.TextField(blank=True, null=True)),
                ('access_water_supply', models.BooleanField(blank=True, null=True)),
                ('potable', models.BooleanField(blank=True, null=True)),
                ('floods_occur', models.BooleanField(blank=True, null=True)),
                ('year_flooded', models.IntegerField(blank=True, null=True)),
                ('experience_evacuate', models.BooleanField()),
                ('year_evacuate', models.IntegerField(blank=True, null=True)),
                ('access_health_medical_facility', models.BooleanField(blank=True, null=True)),
                ('access_telecommuniciation', models.BooleanField(blank=True, null=True)),
                ('access_drill_simulation', models.BooleanField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'household_households',
                'managed': False,
            },
        ),
    ]
