# Generated by Django 4.1 on 2024-01-12 06:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_householdhouseholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_number', models.TextField(blank=True, null=True)),
                ('munname', models.CharField(blank=True, max_length=255, null=True)),
                ('brgyname', models.CharField(blank=True, max_length=255, null=True)),
                ('purok', models.CharField(blank=True, max_length=255, null=True)),
                ('brgycode', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('lat', models.CharField(blank=True, max_length=50, null=True)),
                ('long', models.CharField(blank=True, max_length=50, null=True)),
                ('person', models.BigIntegerField(blank=True, null=True)),
                ('elderly_male', models.BigIntegerField(blank=True, null=True)),
                ('elderly_female', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'point_senior',
                'managed': False,
            },
        ),
    ]
