persons = [
    {
      '_id': '1',
      'name': 'Presidenson Zoilo',
      'image': '/images/airpods.jpg',
      'address':
        'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 170,
      'weight': 60,
    },
    {
      '_id': '2',
      'name': 'Harlequin Samoranos',
      'image': '/images/phone.jpg',
      'address':
        'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 110,
      'weight': 50,
    },
    {
      '_id': '3',
      'name': 'Bryan Jade Mapalo',
      'image': '/images/camera.jpg',
      'address':
        'Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 150,
      'weight': 70,
    },
    {
      '_id': '4',
      'name': 'Rodel Tagupa',
      'image': '/images/playstation.jpg',
      'address':
        'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 140,
      'weight': 70,
    },
    {
      '_id': '5',
      'name': 'Jason Rey Baritua',
      'image': '/images/mouse.jpg',
      'address':
        'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 120,
      'weight': 55,
    },
    {
      '_id': '6',
      'name': 'Glenn Jainar',
      'image': '/images/alexa.jpg',
      'address':
        'Meet Echo Dot - Our most popular smart speaker with a fabric design. It is our most compact smart speaker that fits perfectly into small space',
      'sex': 'Male',
      'birthdate': '04-11-1987',
      'age': 36,
      'occupation': 'IT-Staff',
      'height': 1000,
      'weight': 30,
    }
  ]